apiVersion: v1
kind: Service
metadata:
  name: fastapi-weather-service
spec:
  type: LoadBalancer  
  selector:
    app: fastapi-weather
  ports:
    - protocol: TCP
      port: 80   
      targetPort: 8000  
