apiVersion: v1
kind: Service
metadata:
  name: fastapi-weather-service
spec:
  type: LoadBalancer  # Exposes your API publicly
  selector:
    app: fastapi-weather
  ports:
    - protocol: TCP
      port: 80   # Exposed port
      targetPort: 8000  # The container’s port
